#!/usr/bin/env bash
#
# Shared scheduler-backend logic for claude-keepalive.
#
# Sourced by install.sh (at install time) and by bin/claude-keepalive (for the
# `schedule` subcommand, which rewrites the schedule in place). One file means
# the hours you install with and the hours you switch to later are generated by
# exactly the same code — there is no second source of truth to drift.

BK_PROGRAM="claude-keepalive"

# ---- hooks: callers override these to add dry-run or manifest behaviour ------

bk_run() { "$@"; }
bk_say() { printf '  %s\n' "$*"; }
bk_record() { :; }
bk_write() {
  mkdir -p "$(dirname "$1")"
  printf '%s\n' "$2" >"$1"
}

# ---- scheduler detection ----------------------------------------------------

backend_detect() {
  case "$(uname -s)" in
    Darwin) printf 'launchd' ;;
    Linux)
      if command -v systemctl >/dev/null 2>&1 &&
        systemctl --user show-environment >/dev/null 2>&1; then
        printf 'systemd'
      elif command -v crontab >/dev/null 2>&1; then
        printf 'cron'
      else
        printf 'none'
      fi
      ;;
    *)
      if command -v crontab >/dev/null 2>&1; then printf 'cron'; else printf 'none'; fi
      ;;
  esac
}

# ---- hour lists -------------------------------------------------------------

# "21, 6,11" -> "6,11,21". Rejects anything that is not an hour of the day.
hours_normalize() {
  local h arr out=""
  IFS=',' read -ra arr <<<"$1"
  [ "${#arr[@]}" -gt 0 ] || return 1
  for h in "${arr[@]}"; do
    h="${h//[[:space:]]/}"
    case "$h" in
      '' | *[!0-9]*)
        printf 'not an hour: %s\n' "$h" >&2
        return 1
        ;;
    esac
    h=$((10#$h))
    if [ "$h" -lt 0 ] || [ "$h" -gt 23 ]; then
      printf 'hour out of range 0-23: %s\n' "$h" >&2
      return 1
    fi
    out="${out:+$out,}$h"
  done
  printf '%s' "$out" | tr ',' '\n' | sort -n -u | paste -sd, -
}

# Zero-padded, for systemd's OnCalendar.
hours_pad() {
  local h arr out=""
  IFS=',' read -ra arr <<<"$1"
  for h in "${arr[@]}"; do
    out="${out:+$out,}$(printf '%02d' "$((10#$h))")"
  done
  printf '%s' "$out"
}

# Anchoring only holds when consecutive pings sit exactly WINDOW_HOURS apart:
# each ping then lands at the instant the previous window expires, so the chain
# of windows never drifts. Warn — do not refuse — when it does not hold.
hours_check_spacing() {
  local hours=$1 window=$2 arr h prev="" gap ok=0
  IFS=',' read -ra arr <<<"$hours"
  if [ "${#arr[@]}" -lt 2 ]; then
    return 0
  fi
  for h in "${arr[@]}"; do
    if [ -n "$prev" ]; then
      gap=$((h - prev))
      if [ "$gap" -ne "$window" ]; then
        printf 'warning: %02d:00 -> %02d:00 is %dh apart, but a window lasts %dh.\n' \
          "$prev" "$h" "$gap" "$window" >&2
        ok=1
      fi
    fi
    prev=$h
  done
  if [ "$ok" -ne 0 ]; then
    printf '         Windows will not stay anchored across that gap.\n' >&2
    printf '         An overnight gap is fine and expected; a daytime one is not.\n' >&2
  fi
  return "$ok"
}

# ---- paths ------------------------------------------------------------------

bk_unit_dir() { printf '%s/systemd/user' "${XDG_CONFIG_HOME:-$HOME/.config}"; }
bk_agent_dir() { printf '%s/Library/LaunchAgents' "$HOME"; }

# ---- unit content -----------------------------------------------------------

bk_systemd_service() {
  local bin=$1
  cat <<EOF
[Unit]
Description=Claude Code usage-window keepalive ping
Documentation=https://github.com/SalvadorRGDev/claude-keepalive

[Service]
Type=oneshot
ExecStart=$bin ping

# Deliberately silent: the script keeps its own rotated log. Sending nothing to
# journald means uninstall leaves no residue that would otherwise need
# \`journalctl --vacuum\`, which wipes the whole user journal rather than ours.
StandardOutput=null
StandardError=null
EOF
}

bk_systemd_timer() {
  local hours=$1 padded
  padded=$(hours_pad "$hours")
  # An empty hour list would render as "*-*-* :00:00" -> systemd reads that as
  # midnight, which is valid but silently wrong. Fail loudly instead.
  if [ -z "$padded" ]; then
    printf 'refusing to write a timer with no hours\n' >&2
    return 1
  fi
  cat <<EOF
[Unit]
Description=Schedule claude-keepalive pings

[Timer]
OnCalendar=*-*-* $padded:00:00

# Fire on the minute. Anchoring depends on each ping landing exactly when the
# previous window expires, so jitter is not wanted here.
AccuracySec=1s

# Do NOT catch up on missed runs: a boot-time catch-up would open a window at an
# arbitrary moment, which is precisely the drift this tool exists to prevent.
Persistent=false

[Install]
WantedBy=timers.target
EOF
}

bk_launchd_plist() {
  local bin=$1 hours=$2 h arr
  [ -n "$hours" ] || { printf 'refusing to write a plist with no hours\n' >&2; return 1; }
  printf '<?xml version="1.0" encoding="UTF-8"?>\n'
  printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"\n'
  printf '  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
  printf '<plist version="1.0">\n<dict>\n'
  printf '  <key>Label</key>\n  <string>%s</string>\n' "$BK_PROGRAM"
  printf '  <key>ProgramArguments</key>\n  <array>\n'
  printf '    <string>%s</string>\n    <string>ping</string>\n' "$bin"
  printf '  </array>\n  <key>StartCalendarInterval</key>\n  <array>\n'
  IFS=',' read -ra arr <<<"$hours"
  for h in "${arr[@]}"; do
    printf '    <dict><key>Hour</key><integer>%d</integer>' "$((10#$h))"
    printf '<key>Minute</key><integer>0</integer></dict>\n'
  done
  printf '  </array>\n'
  printf '  <key>RunAtLoad</key>\n  <false/>\n'
  printf '  <key>StandardOutPath</key>\n  <string>/dev/null</string>\n'
  printf '  <key>StandardErrorPath</key>\n  <string>/dev/null</string>\n'
  printf '</dict>\n</plist>\n'
}

# ---- apply ------------------------------------------------------------------

# backend_apply <backend> <bin> <hours>
# Writes and activates the schedule. Idempotent: safe to call again to change
# the hours of an existing install.
backend_apply() {
  local backend=$1 bin=$2 hours=$3

  case "$backend" in
    systemd)
      local dir
      dir=$(bk_unit_dir)
      bk_write "$dir/$BK_PROGRAM.service" "$(bk_systemd_service "$bin")"
      bk_record file "$dir/$BK_PROGRAM.service"
      bk_write "$dir/$BK_PROGRAM.timer" "$(bk_systemd_timer "$hours")"
      bk_record file "$dir/$BK_PROGRAM.timer"
      bk_run systemctl --user daemon-reload
      bk_run systemctl --user enable --now "$BK_PROGRAM.timer"
      bk_record unit "$BK_PROGRAM.timer"
      bk_say "timer set to $(hours_pad "$hours")"
      ;;

    launchd)
      local plist
      plist="$(bk_agent_dir)/$BK_PROGRAM.plist"
      bk_run launchctl unload "$plist" 2>/dev/null || true
      bk_write "$plist" "$(bk_launchd_plist "$bin" "$hours")"
      bk_record agent "$plist"
      bk_run launchctl load "$plist"
      bk_say "agent set to $(hours_pad "$hours")"
      ;;

    cron)
      [ -n "$hours" ] || { printf 'refusing to write a crontab with no hours\n' >&2; return 1; }
      local line="0 $hours * * * $bin ping"
      bk_run bk_cron_replace "$bin" "$line"
      bk_record cron "$bin"
      bk_say "crontab set to $(hours_pad "$hours")"
      ;;

    *)
      printf 'unsupported backend: %s\n' "$backend" >&2
      return 1
      ;;
  esac
}

# Replace our line in the crontab, leaving every other entry untouched.
bk_cron_replace() {
  local bin=$1 line=$2
  {
    crontab -l 2>/dev/null | grep -vF "$bin" || true
    printf '%s\n' "$line"
  } | crontab -
}

# Report the currently active schedule, as the scheduler itself sees it.
backend_show() {
  local backend=$1
  case "$backend" in
    systemd) systemctl --user list-timers "$BK_PROGRAM.timer" --no-pager 2>/dev/null || true ;;
    launchd) launchctl list 2>/dev/null | grep "$BK_PROGRAM" || printf '  (not loaded)\n' ;;
    cron) crontab -l 2>/dev/null | grep "$BK_PROGRAM" || printf '  (no crontab entry)\n' ;;
    *) printf '  (not installed)\n' ;;
  esac
}
